server:
  port: 80

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource: 
    url: jdbc:mysql://localhost:3306/maktaba
    username: maktaba_admin
    password: 1234
  jackson:
    serialization:
      indent_output: true